openapi: 3.0.1
info:
  title: Calendar API
  version: 1.0.0
servers:
  - url: /
tags:
  - name: Credits
  - name: Users
paths:
  /credits:
    get:
      tags:
        - Credits
      summary: Get all credits which created current user
      operationId: get_credits
      responses:
        '200':
          description: credits was successfully returned
          content: {}
        '404':
          description: credits doesn`t found
          content: {}
      x-openapi-router-controller: crud.credits_controller
    post:
      tags:
        - Credits
      summary: Add a new credit to calendar
      operationId: add_credit
      requestBody:
        description: Params for creating credit
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Credit'
        required: true
      responses:
        '201':
          description: credit added
          content: {}
        '400':
          description: Validation failed
          content: {}
      x-codegen-request-body-name: body
      x-openapi-router-controller: crud.credits_controller
  /credits/{credit_id}:
    put:
      tags:
        - Credits
      summary: Update credit in calendar
      operationId: update_credit
      parameters:
        - name: credit_id
          in: path
          description: The id of the credit to update
          required: true
          schema:
            type: integer
      requestBody:
        description: Params for updating credit
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Credit'
        required: false
      responses:
        '201':
          description: credit updated
          content: {}
        '400':
          description: Validation failed
          content: {}
      x-codegen-request-body-name: body
      x-openapi-router-controller: crud.credits_controller
    delete:
      tags:
        - Credits
      summary: Delete credit from calendar
      operationId: delete_credit
      parameters:
        - name: credit_id
          in: path
          description: The id of the credit to remove from the calendar
          required: true
          schema:
            type: integer
      responses:
        '202':
          description: Successfully deleted credit
          content: {}
        '404':
          description: credit doesn`t found
          content: {}
      x-openapi-router-controller: crud.credits_controller
  /credits/{user_id}:
    get:
      tags:
        - Credits
      summary: Get all credits which contains this user
      operationId: get_credits_by_user
      parameters:
        - name: user_id
          in: path
          description: The id of the user to get all credits to which he belongs
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: credits was successfully returned
          content: {}
        '404':
          description: User doesn`t found
          content: {}
      x-openapi-router-controller: crud.credits_controller
  /credits/{credit_id}/{user_id}:
    post:
      tags:
        - Credits
      summary: Add a new user to credit
      operationId: add_user_to_credit
      parameters:
        - name: credit_id
          in: path
          description: The id of the credit to which we add new user
          required: true
          schema:
            type: integer
        - name: user_id
          in: path
          description: The id of the user which need to add to the credit
          required: true
          schema:
            type: integer
      responses:
        '201':
          description: Guest added
          content: {}
        '400':
          description: Validation failed
          content: {}
      x-openapi-router-controller: crud.credits_controller
    delete:
      tags:
        - Credits
      summary: Delete user from credit
      operationId: remove_user_from_credit
      parameters:
        - name: credit_id
          in: path
          description: The id of the credit to which we delete user
          required: true
          schema:
            type: integer
        - name: user_id
          in: path
          description: The id of the user which need to be deleted from the credit
          required: true
          schema:
            type: integer
      responses:
        '201':
          description: Guest added
          content: {}
        '400':
          description: Validation failed
          content: {}
      x-openapi-router-controller: crud.credits_controller
  /users:
    post:
      tags:
        - Users
      summary: Create new user
      operationId: create_user
      requestBody:
        description: Params for creating user
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        '200':
          description: User created
          content: {}
        '400':
          description: Validation failed
          content: {}
      x-openapi-router-controller: crud.users_controller
components:
  schemas:
    Credit:
      required:
      - id_borrower
      - loan_date
      - loan_amount
      - interest_rate
      type: object
      properties:
        id:
          type: integer
          format: int64
        id_borrower:
          type: integer
          format: int64
        loan_status:
          type: boolean
          default: False
        loan_date:
          type: string
          format: data
        loan_amount:
          type: integer
          format: int64
        interest_rate:
          type: integer
          format: int64
          minimum: 0
          maximum: 30
    User:
      required:
      - password
      - username
      type: object
      properties:
        id:
          type: integer
          format: int64
        username:
          type: string
        password:
          type: string
          format: password
        clientName:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        status:
          type: string
          description: User Status
          enum:
            - user
            - manager
