"""first

Revision ID: c39a9fda0b93
Revises: 
Create Date: 2021-11-26 00:14:54.956639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c39a9fda0b93'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('balance',
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('balance')
    )
    op.create_table('users',
    sa.Column('idUsers', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=45), nullable=True),
    sa.Column('password', sa.String(length=60), nullable=True),
    sa.Column('clientName', sa.String(length=45), nullable=True),
    sa.Column('firstName', sa.String(length=45), nullable=True),
    sa.Column('lastName', sa.String(length=45), nullable=True),
    sa.Column('status', sa.Enum('user', 'manager'), nullable=True),
    sa.PrimaryKeyConstraint('idUsers')
    )
    op.create_table('credit',
    sa.Column('idCredit', sa.Integer(), nullable=False),
    sa.Column('loan_status', sa.Boolean(), nullable=True),
    sa.Column('loan_date', sa.String(length=45), nullable=True),
    sa.Column('loan_amount', sa.Integer(), nullable=True),
    sa.Column('interest_rate', sa.Integer(), nullable=True),
    sa.Column('id_borrower', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_borrower'], ['users.idUsers'], ),
    sa.PrimaryKeyConstraint('idCredit')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('credit')
    op.drop_table('users')
    op.drop_table('balance')
    # ### end Alembic commands ###
